[project]
name = "sing-box-subscribe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests",
    "paramiko",
    "scp",
    "chardet",
    "PyYAML",
    "ruamel.yaml",
    "Flask==2.3.2",
]
